#!/usr/bin/env bash
# This Bash script configures a new Ubuntu machine to match the task requirements

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    daemon

defaults
    mode http
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.82.222.41:80 check
    server web-02 54.196.19.105:80 check
EOF

service haproxy restart
