#!/bin/bash
# 1-install_nginx_web_server
# Script to install Nginx and configure root page for Holberton School assignment

# Update package list
apt-get update -y

# Install Nginx
apt-get install -y nginx

# Replace the default page with Holberton School
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx using service (systemctl not allowed)
service nginx restart
