#!/usr/bin/env bash
# Install and configure Nginx web server

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Configure default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure nginx is running (without systemctl)
service nginx start
